import React, { useState } from 'react';
import Head from 'next/head';
import { Inter } from 'next/font/google';
import { UserTypes } from '@/types/userTypes';
import styles from '../styles/Home.module.css';
import Image from 'next/image';
import Link from 'next/link';
const inter = Inter({ subsets: ['latin'] });

interface HomeProps {
  initialData: UserTypes;
}

export default function Home({ initialData }: HomeProps) {
  const [user, setUser] = useState<UserTypes | null>(initialData);
  const [userName, setUserName] = useState<string>('dhashdev');
  console.log('intial data', initialData);
  console.log('user', user);
  //method to get githubUserName
  async function searchGithubUser() {
    try {
      const response = await fetch(`https://api.github.com/users/${userName}`);
      const jsonData: UserTypes = await response.json();
      setUser(jsonData);
    } catch (error) {
      console.log('error');
    }
  }

  //handleing key press
  function handleKeyPress(event: React.KeyboardEvent<HTMLInputElement>) {
    if (event.key === 'Enter') {
      searchGithubUser();
    }
  }
  return (
    <>
      <Head>
        <title>Github Users</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className={styles.container}>
        <h1>Github Users</h1>
        <h2>Please enter a username to search for a user.</h2>
        <input
          type='text'
          placeholder='Enter a username'
          value={userName}
          onChange={(e) => setUserName(e.target.value)}
          onKeyDown={handleKeyPress}
        />
        <button type='button' onClick={searchGithubUser}>
          Search
        </button>
      </div>
      <div className={styles.container}>
        {user && (
          <>
            Name: {user?.name} <div>location: {user.location}</div>
            <div>
              <Image
                src={user.avatar_url}
                alt='user image'
                width={100}
                height={100}
              />
            </div>
            <div>
              <Link href={user.html_url}>Profile URL</Link>
            </div>
            <div>
              followers: {user.followers} following: {user.following}
            </div>
          </>
        )}
      </div>
    </>
  );
}

//getting a default user
export async function getServerSideProps() {
  const response = await fetch('https://api.github.com/users/dhashdev');
  const initialData = await response.json();

  return {
    props: {
      initialData,
    },
  };
}
